#! /bin/sh

# Start input daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Detect and setup monitors
if [[ $(xrandr -q | grep 'HDMI.* connected') ]]; then
	xrandr --output eDP-1-1 --primary --mode 2560x1440 --rotate normal \
		--output HDMI-0 --mode 1920x1200 --rotate normal --right-of eDP-1-1
fi

# BSPWM settings
bspc monitor eDP-1-1 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_radius	3
bspc config border_width       	2
bspc config window_gap          5

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config split_ratio         0.52

bspc config active_border_color '#8ba5ad'
bspc config normal_border_color '#8ba5ad'
bspc config focused_border_color '#8ee6a4'

# App specific rules
bspc rule -a discord state=floating
bspc rule -a lutris state=floating

# Background
feh --bg-scale ~/sources/polybar-themes/wallpapers/bg_17.jpg

# Compositor
picom --config ~/.config/picom/picom.conf -b

# Bar
polybar main &

if [[ $(xrandr -q | grep 'HDMI.* connected') ]]; then
	polybar external-hdmi-0 &
fi

# Other services
dunst &
eww daemon &
systemctl start mpd
betterlockscreen -u "/home/venki/pictures/trees.jpg" &
