#!/bin/sh

# Start input daemon
# TODO: rotate backgrounds...
# (fetch periodically from some website)
pgrep -x sxhkd > /dev/null || sxhkd &

# Detect and setup monitors
sh ~/.config/bspwm/initialize_monitors.sh

# Configure bspwm
bspc config border_radius	0
bspc config border_width       	3
bspc config window_gap          5

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config split_ratio         0.5

bspc config normal_border_color '#a3b8cc'
bspc config focused_border_color '#a5cca3'

# Rules for windows
bspc rule -a Firefox desktop='browser'

# Background
feh --bg-scale ~/pictures/rays.jpg

# Compositor
picom --experimental-backends --xrender-sync-fence --backend glx -b

# Bars
monitors=$(xrandr --query | grep " connected" | cut -d " " -f 1)

# First monitor has all entries, but shows info for others...
polybar -r center &
polybar -r right &
polybar -r left &
polybar -r monitor &

# Other services
alsactl init &
dunst &
mpd &
betterlockscreen -u ~/pictures/dark_sky.png &
libinput-gestures-setup stop desktop autostart start &
polkit-dumb-agent &

# Start Chevron server
# nohup python3 -m http.server --directory ~/sources/chevron/dist/ &

# Other applets
bash /home/venki/scripts/notes/daemon.sh &
