#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_radius	10
bspc config border_width         2
bspc config window_gap          16

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config split_ratio          0.52

feh --bg-scale pictures/724910.webp

picom --config ~/.config/picom/picom.conf -b
